# Generated by Django 4.0.2 on 2022-02-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
