# Generated by Django 4.0.2 on 2022-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_post_date_of_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
