# Generated by Django 4.0.2 on 2022-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_post_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
